# Generated by Django 2.1.1 on 2019-04-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, unique=True)),
                ('emp_age', models.IntegerField(unique=True)),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginApp.department')),
            ],
        ),
    ]
